services:
  redis:
    image: redis:7-alpine
    container_name: local-platform-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./services/api
    container_name: local-platform-api
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  worker:
    build:
      context: ./services/worker
    container_name: local-platform-worker
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
  
  prometheus:
    image: prom/prometheus
    container_name: local-platform-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker

  grafana:
    image: grafana/grafana
    container_name: local-platform-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus