apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: microservices-platform
spec:
  type: NodePort
  selector:
    app: api-service
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30081